markdown: rdiscount
highlighter: 'pygments'
pygments: true
paginate: 10
permalink: /title

title: Elliot
url: "https://elliotsomething.github.io/" 
feed: /atom.xml
author_info: <a href="https://Elliotsomething.github.io/">Mukosame</a>
